---
name: Smartphoton
version: 0.0.36
slug: smartphoton
description: Smartphoton
url: https://domosimple.eu/
ingress: false
#ingress_port: 1890
ingress_stream: false
webui: http://[HOST]:[PORT:1890]
panel_icon: mdi:sitemap
init: false
homeassistant: 2021.3.0
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  1890/tcp: 1890
ports_description:
  1890/tcp: Web interface
hassio_api: true
hassio_role: manager
homeassistant_api: true
host_network: true
auth_api: true
uart: true
map:
  - config:rw
  - media:rw
  - share:rw
  - ssl
options:
  onduleur: 
  usbonduleur: 
  elfinonduleur: false
  elfinonduleurip: Adresse ip
  elfinonduleurport: 7777
  batterie: 
  usbbatterie: 
  elfinbatterie: false
  elfinbatterieip: Adresse ip
  elfinbatterieport: 7777
  mqtt: Adresse du serveur
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  onduleur: list(voltronic|easun)
  usbonduleur: device(subsystem=tty)?
  elfinonduleur: bool
  elfinonduleurip: str?
  elfinonduleurport: port?
  batterie: list(pylontech|jkbms)?
  usbbatterie: device(subsystem=tty)?
  elfinbatterie: bool
  elfinbatterieip: str?
  elfinbatterieport: port?
  mqtt: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
  not_need: "str?"
  leave_front_door_open: bool?
  safe_mode: bool?
  max_old_space_size: int?
